/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FerreGui;

import ferrefactura.Clases.CommandHandler.ProductoRepository;
import ferrefactura.negocios.acciones.commands.CreateProducto;
import javax.swing.JOptionPane;

/**
 *
 * @author steve
 */
public class Clientesgui extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientesgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 630, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apoyo-tecnico.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 260, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        jMenu1.setText("Facturas");

        jMenuItem1.setText("Buscar");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Crear");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Productos");

        jMenuItem2.setText("Buscar");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
     
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
  

   
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del producto:");
        
        // Validamos que el campo no esté vacío
        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre no puede estar vacío.");
            return;
        }

        // Solicitar el ID (convertido a entero)
        String idStr = JOptionPane.showInputDialog("Ingrese el ID del producto:");
        int id;
        try {
            id = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un número entero.");
            return;
        }

        // Solicitar el precio (convertido a doble)
        String precioStr = JOptionPane.showInputDialog("Ingrese el precio del producto:");
        double Precio;
        try {
            Precio = Double.parseDouble(precioStr);
            if (Precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor que 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un número decimal.");
            return;
        }

        // Solicitar la cantidad de ventas
        String cantidadVentasStr = JOptionPane.showInputDialog("Ingrese la cantidad de ventas:");
        int CantidadVentas;
        try {
            CantidadVentas = Integer.parseInt(cantidadVentasStr);
            if (CantidadVentas <= 0) {
                JOptionPane.showMessageDialog(null, "La cantidad de ventas debe ser mayor que 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad de ventas debe ser un número entero.");
            return;
        }

        // Solicitar la descripción
        String Descripcion = JOptionPane.showInputDialog("Ingrese una descripción del producto:");
        
        // Validamos que la descripción no esté vacía
        if (Descripcion == null || Descripcion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La descripción no puede estar vacía.");
            return;
        }

        // Solicitar la calidad con opciones predefinidas
        String Calidad = JOptionPane.showInputDialog("Ingrese la calidad del producto (Opciones: Buena, Excelente, Media, Mala, Pesima):");
        String[] opcionesCalidad = {"Buena", "Excelente", "Media", "Mala", "Pesima"};
        boolean calidadValida = false;

        for (String opcion : opcionesCalidad) {
            if (opcion.equalsIgnoreCase(Calidad)) {
                calidadValida = true;
                break;
            }
        }

        if (!calidadValida) {
            JOptionPane.showMessageDialog(null, "La calidad debe ser una de las siguientes opciones: Buena, Excelente, Media, Mala, Pesima.");
            return;
        }

        // Solicitar la cantidad en almacén
        String cantidadAlmacenStr = JOptionPane.showInputDialog("Ingrese la cantidad en almacén:");
        int CantidadAlmacen;
        try {
            CantidadAlmacen = Integer.parseInt(cantidadAlmacenStr);
            if (CantidadAlmacen < 0) {
                JOptionPane.showMessageDialog(null, "La cantidad en almacén no puede ser negativa.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad en almacén debe ser un número entero.");
            return;
        }

       
      
    

 

        
        CreateProducto productoNuevo = new CreateProducto(nombre, id, MAXIMIZED_VERT, Descripcion, ERROR, Calidad, EXIT_ON_CLOSE);
        ProductoRepository guardar = new ProductoRepository();
        guardar.save(productoNuevo);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
